# Generated by Django 4.2.19 on 2025-02-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_scheduletask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletask',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_tasks', to='students.group'),
        ),
    ]
