# Generated by Django 4.2.19 on 2025-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='thread_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
